version: '2'
services:
  markers:
    image: jeguzzi/thymioid
    command: roslaunch --wait thymioid ar_cubes.launch
    env_file:
      - ../../ros.env
    volumes:
      - ../../logs:/root/.ros/log:rw
    network_mode: host
