version: '3'
services:
  core:
    image: jeguzzi/ros:armhf-kinetic-ros-dev
    network_mode: host
    command: roscore
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
  robot:
    build: .
    image: jeguzzi/thymioid
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid robot.launch
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  camera:
    image: jeguzzi/thymioid
    network_mode: host
    privileged: true
    restart: always
    command: roslaunch --wait thymioid camera.launch image_width:=640 image_height:=480 rectify:=false
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  ups:
    image: jeguzzi/thymioid
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid ups.launch
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  ui:
    image: jeguzzi/thymioid
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid ui.launch
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - /var/run/dbus:/var/run/dbus
      - /run/systemd:/run/systemd
      - /usr/bin/systemctl:/usr/bin/systemctl
      - /etc/systemd/system:/etc/systemd/system
      - /run/network/ifstate.wlan0:/run/network/ifstate.wlan0
      - ./wlan:/wlan:rw
  jupyter:
    image: jeguzzi/thymioid
    network_mode: host
    command: jupyter notebook --allow-root --NotebookApp.token='' --port=8888 --no-browser --notebook-dir=/root/docker/mighty-thymio/notebook --ip=0.0.0.0
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
  portainer:
    image: portainer/portainer:linux-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: always
