version: '3'
services:
  core:
    image: jeguzzi/ros:armhf-melodic-ros-dev
    network_mode: host
    command: roscore
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
  robot:
    build:
      context: .
      dockerfile: Dockerfile-melodic
    image: jeguzzi/thymioid:melodic
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid robot.launch odom_max_rate:=21
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - /dev:/dev
      - ./calibration:/root/catkin_ws/src/ros-aseba/thymio_driver/calibration:rw
    depends_on:
      - core
  camera:
    image: jeguzzi/thymioid:melodic
    network_mode: host
    privileged: true
    restart: always
    command: roslaunch --wait thymioid camera.launch framerate:=15 image_width:=640 image_height:=480 rectify:=false
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  speaker:
    image: jeguzzi/thymioid-audio:melodic
    network_mode: host
    privileged: true
    restart: always
    command: roslaunch --wait mt_sound sound.launch device:="hw:1,0"
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./sounds:/root/catkin_ws/src/mt_speaker/sound
    depends_on:
      - core
  screen:
    image: jeguzzi/thymioid-screen:melodic
    network_mode: host
    privileged: true
    command: rosrun tft tft_node.py tft/image:=camera/image_raw
    restart: always
    env_file:
      - ./ros.env
    environment:
      - ROS_NAMESPACE=$HOSTNAME
    volumes:
      - ./logs:/root/.ros/log:rw
      - /dev:/dev
  touch:
    image: jeguzzi/thymioid-screen:melodic
    network_mode: host
    privileged: true
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - /dev:/dev
      - ./calibration/pointercal:/usr/local/etc/pointercal
    command: roslaunch tft touch.launch
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
      - TSLIB_TSDEVICE=/dev/input/event1
  ups:
    image: jeguzzi/thymioid:melodic
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid ups.launch
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  ui:
    image: jeguzzi/thymioid:melodic
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid ui.launch
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - /run/network/ifstate.wlan0:/run/network/ifstate.wlan0
      - ./wlan:/wlan:rw
      - ./shutdown:/shutdown:rw
      - ./update:/update:rw
    depends_on:
      - robot
  demos:
    image: jeguzzi/thymioid:melodic
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid demo_menu.launch demos:=[ml,markers]
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - /var/run/docker.sock:/var/run/docker.sock
  joy_teleop:
    image: jeguzzi/thymioid:melodic
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid joy_teleop.launch
    restart: always
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
  notebook:
    image: jeguzzi/thymioid:melodic
    network_mode: host
    command: jupyter notebook --allow-root --NotebookApp.token='' --port=8888 --no-browser --notebook-dir=/notebook --ip=0.0.0.0
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./notebook:/notebook:rw
  portainer:
    command: --no-auth
    image: portainer/portainer:linux-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: always
  aseba:
    image: jeguzzi/thymioid:melodic
    command: /root/catkin_ws/devel/lib/aseba/asebaswitch "ser:device=/dev/ttyACM0"
    privileged: true
    # restart: none
    ports:
      - 33333:33333
