version: '2'
services:
  core:
    image: jeguzzi/ros:armhf-kinetic-ros-dev
    network_mode: host
    command: roscore
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
  robot:
    build: .
    image: jeguzzi/thymiod
    network_mode: host
    privileged: true
    command: roslaunch thymioid robot.launch
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  camera:
    image: jeguzzi/thymiod
    network_mode: host
    privileged: true
    command: roslaunch thymioid camera.launch
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  ups:
    image: jeguzzi/thymiod
    network_mode: host
    privileged: true
    command: roslaunch thymioid ups.launch
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    depends_on:
      - core
  ui:
    image: jeguzzi/thymiod
    network_mode: host
    privileged: true
    command: roslaunch thymioid ui.launch
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
  portainer:
    image: portainer/portainer:linux-arm
    # command: --host=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
  demo:
    image: jeguzzi/thymioid:demo_ml
    command: roslaunch thymio_controller headless_demo.launch
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    network_mode: host
    depends_on:
      - core
  stream:
    image: jeguzzi/thymioid:demo_ml
    command: roslaunch thymio_controller stream.launch
    env_file:
      - ./ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    network_mode: host
    depends_on:
      - core
